import type { Metadata } from "next";
import { Roboto } from "@next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ReactQueryClientProviders } from "@/lib/react-query-client-provider";

// Import the Roboto font
const roboto = Roboto({
  weight: ["400", "500", "700"], // Specify the weights you need
  subsets: ["latin"], // Choose the subsets you want
  variable: "--font-roboto", // Optional: use this variable to apply the font via CSS variable
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: {
  authToken: string;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <Toaster />
        <main>
          <ReactQueryClientProviders>{children}</ReactQueryClientProviders>
        </main>
      </body>
    </html>
  );
}
